servers:

  # Server that listens on 443/80
  - bind:
    - address: '*:443'
      # certificate can be a section name, 'letsencrypt', or 'dev'
      certificate: dev
      protocols:
      - http2
    - address: '*:80'
      protocols:
      - http1

    # Optional HTTPS redirection
    httpsRedirection:
        enabled: false
        # port: 443

    rewrite:
    - from: ^rewrite-rule/(\d+)/(\d+)
      to: rewritten?var1=$1&var2=$2
      # skipRemainingRules: false

    redirect:
    - from: redirect-rule/(.*)
      to: redirected/$1

    endpoints:

    # File-content mapping
    - route: /
      file:
        path: Content/index.html
      contentType: text/html

    # Static files middleware mapping
    - route: /static
      files:
        path: wwwroot

    # Raw content responses
    - route: /plaintext
      body: <h1>Hello World<h1>
      contentType: text/html
      rateLimit:
        policy: nottoofast
    
    # Custom response Content Type 
    - route: /json
      body: '{ message: "Hello world" }'
      contentType: application/json

    # File content result
    - route: /favicon.ico
      contentType: image/x-icon
      file:
        path: wwwroot/favicon.ico

    # Redirections
    - route: /markdown
      redirect: /markdown/1

    # Verb mapping
    - route: /method
      body: From GET

    - route: /method
      body: From POST
      methods: post

    responseCompression:
      enabled: true

  # Server that listens on 81, shows caching and endpoint groups
  - bind:
    - address: localhost:81
    
    # Example of an endpoint group where output caching is applied on all endpoints
    endpoints:
    - route: /*
      cache:
        duration: 2s
        # Cache settings can be inlined, or from a shared policy
        policy: long

    - route: /monster
      body: '<img src="https://www.gravatar.com/avatar/abcde?s=200&d=monsterid"/>'
      contentType: text/html

  # Server that listens on 8080 and proxies /google and /microsoft to external domains
  - bind:
    - address: localhost:8080
    
    # protocols: http3 # defaults to http1 and http2
    # certificate:

    endpoints:
    - route: /
      body: <h1>Proxies<h1>
      contentType: text/html

    - route: /google
      proxy:
        destination: https://www.google.com

    - route: /microsoft
      proxy:
        destination: https://www.microsoft.com/en-us
        # There is a custom "transform" to remove the prefix (/microsoft) from the
        # proxied requests
        # removePrefix: false 
  
  # Custom Reverse Proxy configuration
  - bind:
    - address: localhost:8081
  
    # c.f. https://microsoft.github.io/reverse-proxy/articles/config-files.html
    reverseProxy: 
      routes:
        - routeId: route1
          clusterId: cluster1
          match:
            path: "{**catch-all}"
            # hosts:
            #   - www.aaaaa.com
            #   - www.bbbbb.com
      clusters:
        - clusterId: cluster1
          destinations:
            cluster1/destination1:
              address: https://example.com/
  
cachePolicies:
  - name: long
    duration: 5s

rateLimitPolicies:
  - name: nottoofast
    duration: 5s
    permit: 3
    #queue: 1

certificates:
  - name: testCert
    path: testCert.pfx
    password: testPassword

letsEncrypt:
  path: ./.certificates
  email: youremail@microsoft.com
  domains: 
  - yourdomain.com
